---
title: "ClimateDist_Comp"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Comparing water year and growth season climate distances

## Libraries
```{r}
library(tidyverse)
library(lmerTest) #mixed models
library(geosphere) #for calculating geographic distance
```

## Load Gower's Distance

```{r}
wl2_gowers_2023 <- read_csv("../output/Climate/Gowers_WL2.csv") %>% 
  select(parent.pop:GrwSsn_GD, Wtr_Year_GD) %>% 
  pivot_wider(names_from = TimePd, values_from = c(GrwSsn_GD, Wtr_Year_GD)) %>% 
  mutate(WL2_Lat=38.82599, WL2_Long=-120.2509, WL2_Elev=2020) %>% 
  mutate(Geographic_Dist=distHaversine(cbind(WL2_Long, WL2_Lat), cbind(Long, Lat)),
         Elev_Dist=elev_m-WL2_Elev) %>% # Calculate the distance using the haversine formula
  rename(pop=parent.pop)

wl2_gowers_2324 <- read_csv("../output/Climate/Gowers_WL2_2324.csv") %>% 
  select(parent.pop:GrwSsn_GD, Wtr_Year_GD) %>% 
  pivot_wider(names_from = TimePd, values_from = c(GrwSsn_GD, Wtr_Year_GD)) %>% 
  mutate(WL2_Lat=38.82599, WL2_Long=-120.2509, WL2_Elev=2020) %>% 
  mutate(Geographic_Dist=distHaversine(cbind(WL2_Long, WL2_Lat), cbind(Long, Lat)),
         Elev_Dist=elev_m-WL2_Elev) %>% # Calculate the distance using the haversine formula
  rename(pop=parent.pop)
```

## Stats
```{r}
wl2_gowers_2023_recent <- wl2_gowers_2023 %>% 
  select(pop:GrwSsn_GD_Recent, Wtr_Year_GD_Recent) %>% 
  pivot_longer(cols = ends_with("Recent"),
               names_to = "Season",
               values_to = "GD")

mod_2023_recent <- lmer(GD ~ Season + (1|pop), data=wl2_gowers_2023_recent)
summary(mod_2023_recent)

wl2_gowers_2023_hist <- wl2_gowers_2023 %>% 
  select(pop:GrwSsn_GD_Historical, Wtr_Year_GD_Historical) %>% 
  pivot_longer(cols = ends_with("Historical"),
               names_to = "Season",
               values_to = "GD")

mod_2023_hist <- lmer(GD ~ Season + (1|pop), data=wl2_gowers_2023_hist)
summary(mod_2023_hist)
```

```{r}
wl2_gowers_2324_recent <- wl2_gowers_2324 %>% 
  select(pop:GrwSsn_GD_Recent, Wtr_Year_GD_Recent) %>% 
  pivot_longer(cols = ends_with("Recent"),
               names_to = "Season",
               values_to = "GD")

mod_2324_recent <- lmer(GD ~ Season + (1|pop), data=wl2_gowers_2324_recent)
summary(mod_2324_recent)

wl2_gowers_2324_hist <- wl2_gowers_2324 %>% 
  select(pop:GrwSsn_GD_Historical, Wtr_Year_GD_Historical) %>% 
  pivot_longer(cols = ends_with("Historical"),
               names_to = "Season",
               values_to = "GD")

mod_2324_hist <- lmer(GD ~ Season + (1|pop), data=wl2_gowers_2324_hist)
summary(mod_2324_hist)
```