---
title: "Post_Winter_Size"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Post-Winter Size at WL2

## Relevant Libraries and Functions

```{r}
library(tidyverse)
library(lmerTest) #for mixed effect models
library(emmeans) #for post-hoc pairwise comparisons 
library(naniar) #replaces values with NA
library(ggnewscale)
library(corrplot) #plotting correlations 
library(geosphere) #for calculating geographic distance
conflicted::conflicts_prefer(lmerTest::lmer)
conflicted::conflicts_prefer(dplyr::filter)

sem <- function(x, na.rm=FALSE) {           #for calculating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
} 

elev_three_palette <- c("#0043F0", "#C9727F", "#F5A540") #colors from Gremer et al 2019
elev_order <- c("High", "Mid", "Low") #for proper arrangement in figures 
```

## Load Size data

```{r}
wl2_y2_pops <- read_csv("../input/WL2_Data/Final_2023_2024_Pop_Loc_Info.csv") %>%
  select(Pop.Type:unique.ID) %>% 
  filter(Pop.Type=="2023-survivor") %>% 
  select(Pop.Type, loc:bed, row=bedrow, col=bedcol, pop:unique.ID)

wl2_blocks <- read_csv("../input/WL2_Data/CorrectedCSVs/WL2_mort_pheno_20231020_corrected.csv") %>% 
  unite(BedLoc, bed:bed.col, sep="_", remove = FALSE) %>% 
  filter(BedLoc!="K_5_C") %>% #get rid of duplicate locations
  select(block, pop, mf, rep) %>% #add in block info 
  mutate(mf=as.double(mf), rep=as.double(rep)) #convert to num

wl2_y2_pops_blocks <- left_join(wl2_y2_pops, wl2_blocks)

wl2_post_winter_2024 <- read_csv("../input/WL2_Data/WL2_size_survey_20240618_2023Plants_corrected.csv") %>% filter(Pop.Type!="2023-TM2-fruit") %>% select(-block, -wrongID)
wl2_post_winter_2024_pops <- left_join(wl2_y2_pops_blocks, wl2_post_winter_2024) %>%  
  rename(Genotype=unique.ID)

write_csv(wl2_post_winter_2024_pops, "../output/WL2_Traits/WL2_PostWinter_Size.csv")
```

## Load the pop and location data

```{r}
wl2_gowers_2024 <- read_csv("../output/Climate/Gowers_WL2_2024.csv") %>% 
  pivot_wider(names_from = TimePd, values_from = c(GrwSsn_GD, Wtr_Year_GD)) %>% 
  mutate(WL2_Lat=38.82599, WL2_Long=-120.2509, WL2_Elev=2020) %>% 
  mutate(Geographic_Dist=distHaversine(cbind(WL2_Long, WL2_Lat), cbind(Long, Lat)),
         Elev_Dist=elev_m-WL2_Elev) %>% # Calculate the distance using the haversine formula
  rename(pop=parent.pop)
```

## Add in location info

```{r}
wl2_post_winter_2024_pops_loc <- left_join(wl2_post_winter_2024_pops, wl2_gowers_2024)
head(wl2_post_winter_2024_pops_loc)
```

## Pop Trends
```{r}
wl2_post_winter_2024_pops_loc %>% 
  filter(!is.na(height.cm)) %>% 
  ggplot(aes(x=pop, y=height.cm)) +
  geom_boxplot()

wl2_post_winter_2024_pops_loc %>% 
  filter(!is.na(long.leaf.cm)) %>% 
  ggplot(aes(x=pop, y=long.leaf.cm)) +
  geom_boxplot()
```

```{r}
wl2_post_winter_2024_summary <- wl2_post_winter_2024_pops_loc %>% 
  group_by(pop, elev_m) %>% 
  summarise(N_height = sum(!is.na(height.cm)), 
            mean_height.cm = mean(height.cm, na.rm=TRUE), sem_height.cm=sem(height.cm, na.rm=TRUE), 
            N_length = sum(!is.na(long.leaf.cm)),
            mean_long.leaf.cm=mean(long.leaf.cm, na.rm=TRUE), sem_long.leaf.cm=sem(long.leaf.cm, na.rm=TRUE))

wl2_post_winter_2024_summary %>% arrange(N_height) 
#Sample size too low for LV1, SQ1, WR
#different sample sizes depending on the trait 
```

```{r}
wl2_post_winter_2024_summary %>% 
  filter(N_height>2) %>% 
  ggplot(aes(x=fct_reorder(pop, mean_height.cm), y=mean_height.cm, fill=elev_m)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_height.cm-sem_height.cm,ymax=mean_height.cm+sem_height.cm),width=.2, 
                position = position_dodge(0.75)) +
  theme_classic() + 
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(y="Avg Height (cm)", x="Parent Population", fill="Elevation (m)") +
  scale_fill_gradient(low = "#F5A540", high = "#0043F0")  +
  theme(text=element_text(size=30), axis.text.x = element_text(angle = 45,  hjust = 1))

wl2_post_winter_2024_summary %>% 
  filter(N_length>2) %>% 
  ggplot(aes(x=fct_reorder(pop, mean_long.leaf.cm), y=mean_long.leaf.cm, fill=elev_m)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_long.leaf.cm-sem_long.leaf.cm,ymax=mean_long.leaf.cm+sem_long.leaf.cm),width=.2, 
                position = position_dodge(0.75)) +
  theme_classic() + 
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(y="Avg Leaf Length (cm)", x="Parent Population", fill="Elevation (m)") +
  scale_fill_gradient(low = "#F5A540", high = "#0043F0")  +
  theme(text=element_text(size=30), axis.text.x = element_text(angle = 45,  hjust = 1))
```

