---
title: "Single Time Size Reaction Norms"
author: "Brandie Quarles"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Reaction Norms of Size (between UCD and WL2)

## Relevant Libraries and Functions

```{r}
library(tidyverse)
library(tidymodels)
tidymodels_prefer()
library(lmerTest) #for mixed effect models
conflicted::conflicts_prefer(lmerTest::lmer)
library(broom.mixed) #tidy method for lmerTest
library(emmeans) #for post-hoc pairwise comparisons 
library(naniar) #replaces values with NA
library(corrplot) #plotting correlations 
library(rstatix) #performing cor_test
sem <- function(x, na.rm=FALSE) {           #for caclulating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
} 

elev_three_palette <- c("#0043F0", "#C9727F", "#F5A540") #colors from Gremer et al 2019
elev_order <- c("High", "Mid", "Low") #for proper arrangement in figures 
```

## Load the pop and location data

```{r}
#pop info
pops_common_garden <- read_csv("../input/WL2_Data/Pops_for_2023_WL2.csv") #pops included in common garden 
summary(pops_common_garden)
pops_common_garden_nonotes <- pops_common_garden %>% select(parent.pop:`seed year`)
pops_common_garden_nonotes$elevation.group <- str_to_title(pops_common_garden_nonotes$elevation.group)

#extra location info 
pop_loc <- read_csv("../input/Strep_tort_locs.csv")

unique(pop_loc$`Site code`)
unique(pops_common_garden_nonotes$parent.pop)
#need to change YOSE to YO
pop_loc_yo <- pop_loc %>% mutate(parent.pop = str_replace(`Site code`, "YOSE(\\d+)", "YO\\1")) %>% select(Lat, Long, elev_m=`Elevation (m)`, parent.pop)
unique(pop_loc_yo$parent.pop)

#merge in location info
pop_elev <- left_join(pops_common_garden_nonotes, pop_loc_yo)
head(pop_elev)
```

## Load Size data from both Gardens
Starting with just 2 months in the field 
```{r}
WL2_twomonths_size <- read_csv("../input/WL2_Data/CorrectedCSVs/WL2_size_survey_20230913_corrected.csv", 
                               na = c("", "NA", "-", "N/A")) %>% 
  rename(parent.pop=pop) %>% 
  mutate(parent.pop= str_replace(parent.pop, ".*VTR.*", "LVTR1")) %>% 
  unite(Genotype, parent.pop:rep, sep="_", remove = FALSE) 
head(WL2_twomonths_size)
dim(WL2_twomonths_size)
summary(WL2_twomonths_size)
WL2_twomonths_size %>% rowwise() %>% filter(!is.na(mf), mf != "buffer") %>%  filter(is.na(as.numeric(mf)))
WL2_twomonths_size %>% rowwise() %>% filter(!is.na(rep), rep != "buffer") %>%  filter(is.na(as.numeric(rep))) #all buffer rows 

UCD_twomonths_size <- read_csv("../input/UCD_Data/CorrectedCSVs/Size_survey_transplants_20230127_corrected.csv", 
                               na = c("", "NA", "-", "N/A")) %>% 
  rename(height.cm = `height (cm)`, long.leaf.cm = `longest leaf (cm)`, parent.pop=pop) %>% 
  mutate(parent.pop= str_replace(parent.pop, ".*VTR.*", "LVTR1")) %>% 
  filter(rep != 100)  %>% #get rid of individuals that germinated in the field 
  unite(Genotype, parent.pop:rep, sep="_", remove = FALSE)
head(UCD_twomonths_size)
dim(UCD_twomonths_size)
summary(UCD_twomonths_size)

UCD_twomonths_size %>% filter(!is.na(...10)) #extra notes 
```

## Merge the Data
```{r}
WL2_twomonths_size_prep <- WL2_twomonths_size %>% select(Genotype:long.leaf.cm) %>% mutate(Site="WL2") %>%
  mutate(mf=as.double(mf), rep=as.double(rep))
names(WL2_twomonths_size_prep)

UCD_twomonths_size_prep <- UCD_twomonths_size %>% select(Genotype:long.leaf.cm) %>% mutate(Site="UCD")
names(UCD_twomonths_size_prep)

twomonths_rxnnorms <- bind_rows(UCD_twomonths_size_prep, WL2_twomonths_size_prep) %>% 
  filter(!str_detect(Genotype, ".*buffer.*")) %>% 
  filter(!is.na(height.cm)) %>% 
  arrange(Genotype, Site)
#xtabs(~Genotype+Site, data=twomonths_rxnnorms)
head(twomonths_rxnnorms)

twomonths_rxnnorms_siten <- twomonths_rxnnorms %>% group_by(Genotype) %>% summarise(SiteN=sum(!is.na(Genotype))) %>% filter(SiteN==2)
twomonths_rxnnorms_siten

twomonths_rxnnorms_bothsites <- left_join(twomonths_rxnnorms_siten, twomonths_rxnnorms)
dim(twomonths_rxnnorms_bothsites)
head(twomonths_rxnnorms_bothsites)
unique(twomonths_rxnnorms_bothsites$parent.pop)
xtabs(~parent.pop + Site, data=twomonths_rxnnorms_bothsites)
```

## Add in location info
```{r}
twomonths_rxnnorms_bothsites_loc <- left_join(twomonths_rxnnorms_bothsites, pop_elev)
head(twomonths_rxnnorms_bothsites_loc)
```


## Plot Reaction Norms
All Genotypes Colored by Pop
```{r}
twomonths_rxnnorms_bothsites_loc %>% 
  ggplot(aes(x=Site, y=height.cm, group=Genotype, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  theme_classic() +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_Height_All_Genos.png", width = 12, height = 8, units = "in")

twomonths_rxnnorms_bothsites_loc %>% 
  ggplot(aes(x=Site, y=long.leaf.cm, group=Genotype, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  theme_classic()  +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_LongestLength_All_Genos.png", width = 12, height = 8, units = "in")
```
All Genotypes colored by elevation
```{r}
twomonths_rxnnorms_bothsites_loc %>% 
  ggplot(aes(x=Site, y=height.cm, group=Genotype, color=elev_m)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  theme_classic() + scale_colour_gradient(low = "#F5A540", high = "#0043F0")

twomonths_rxnnorms_bothsites_loc %>% 
  ggplot(aes(x=Site, y=long.leaf.cm, group=Genotype, color=elev_m)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  theme_classic() + scale_colour_gradient(low = "#F5A540", high = "#0043F0")
```

Just TM2 and WL2
```{r}
twomonths_rxnnorms_bothsites_loc %>% 
  filter(parent.pop=="TM2"|parent.pop=="WL2") %>% 
  ggplot(aes(x=Site, y=height.cm, group=Genotype, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  theme_classic()  +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_Height_TM2_WL2_Genos.png", width = 12, height = 8, units = "in")

twomonths_rxnnorms_bothsites_loc %>% 
  filter(parent.pop=="TM2"|parent.pop=="WL2") %>% 
  ggplot(aes(x=Site, y=long.leaf.cm, group=Genotype, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  theme_classic()  +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_LongestLength_TM2_WL2_Genos.png", width = 12, height = 8, units = "in")
```


Means by Pop
```{r}
twomonths_rxnnorms_summary <- twomonths_rxnnorms_bothsites_loc %>% 
  group_by(parent.pop, Site, elev_m) %>% 
  summarise(N_height = sum(!is.na(height.cm)), mean_height.cm = mean(height.cm,na.rm=(TRUE)), 
            sem_height.cm=sem(height.cm, na.rm=(TRUE)), N_length = sum(!is.na(long.leaf.cm)),
            mean_long.leaf.cm=mean(long.leaf.cm, na.rm=(TRUE)), 
            sem_long.leaf.cm=sem(long.leaf.cm, na.rm=TRUE))
twomonths_rxnnorms_summary
```

Plot Pop Avgs
```{r}
twomonths_rxnnorms_summary %>% 
   ggplot(aes(x=Site, y=mean_height.cm, group=parent.pop, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_height.cm-sem_height.cm,ymax=mean_height.cm+sem_height.cm),width=.2) +
  theme_classic() +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_Height_ALL_PopAvgs2.png", width = 12, height = 8, units = "in")

twomonths_rxnnorms_summary %>% 
   ggplot(aes(x=Site, y=mean_long.leaf.cm, group=parent.pop, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_long.leaf.cm-sem_long.leaf.cm,ymax=mean_long.leaf.cm+sem_long.leaf.cm),width=.2) +
  theme_classic() +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_LongestLength_ALL_PopAvgs2.png", width = 12, height = 8, units = "in")
```

```{r}
twomonths_rxnnorms_summary %>% 
   ggplot(aes(x=Site, y=mean_height.cm, group=parent.pop, color=elev_m)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_height.cm-sem_height.cm,ymax=mean_height.cm+sem_height.cm),width=.2) +
  theme_classic() + scale_colour_gradient(low = "#F5A540", high = "#0043F0")  +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_Height_ALL_PopAvgs.png", width = 12, height = 8, units = "in")

twomonths_rxnnorms_summary %>% 
   ggplot(aes(x=Site, y=mean_long.leaf.cm, group=parent.pop, color=elev_m)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_long.leaf.cm-sem_long.leaf.cm,ymax=mean_long.leaf.cm+sem_long.leaf.cm),width=.2) +
  theme_classic() + scale_colour_gradient(low = "#F5A540", high = "#0043F0")  +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_LongestLength_ALL_PopAvgs.png", width = 12, height = 8, units = "in")
```

```{r}
twomonths_rxnnorms_summary %>% 
  filter(parent.pop=="TM2"|parent.pop=="WL2") %>%  
   ggplot(aes(x=Site, y=mean_height.cm, group=parent.pop, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_height.cm-sem_height.cm,ymax=mean_height.cm+sem_height.cm),width=.2) +
  theme_classic()  +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_Height_TM2_WL2_PopAvgs.png", width = 12, height = 8, units = "in")

twomonths_rxnnorms_summary %>% 
  filter(parent.pop=="TM2"|parent.pop=="WL2") %>%  
   ggplot(aes(x=Site, y=mean_long.leaf.cm, group=parent.pop, color=parent.pop)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_long.leaf.cm-sem_long.leaf.cm,ymax=mean_long.leaf.cm+sem_long.leaf.cm),width=.2) +
  theme_classic()  +
   theme(text=element_text(size=25))
ggsave("../output/TwoMonths_RxNorms_LongestLength_TM2_WL2_PopAvgs.png", width = 12, height = 8, units = "in")
```


Means by Elevation
```{r}
twomonths_rxnnorms_summary2 <- twomonths_rxnnorms_bothsites_loc %>% 
  group_by(elevation.group, Site) %>% 
  summarise(N_height = sum(!is.na(height.cm)), mean_height.cm = mean(height.cm,na.rm=(TRUE)), 
            sem_height.cm=sem(height.cm, na.rm=(TRUE)), N_length = sum(!is.na(long.leaf.cm)),
            mean_long.leaf.cm=mean(long.leaf.cm, na.rm=(TRUE)), 
            sem_long.leaf.cm=sem(long.leaf.cm, na.rm=TRUE))
twomonths_rxnnorms_summary2
```


```{r}
twomonths_rxnnorms_summary2$elevation.group <- factor(twomonths_rxnnorms_summary2$elevation.group, levels = c('High','Mid', 'Low'))
twomonths_rxnnorms_summary2 %>% 
   ggplot(aes(x=Site, y=mean_height.cm, group=elevation.group, color=elevation.group)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_height.cm-sem_height.cm,ymax=mean_height.cm+sem_height.cm),width=.2) +
  theme_classic() + scale_colour_manual(values=elev_three_palette)

twomonths_rxnnorms_summary2 %>% 
   ggplot(aes(x=Site, y=mean_long.leaf.cm, group=elevation.group, color=elevation.group)) + 
  geom_point(size=0.8) + geom_line(linewidth=0.8) +
  geom_errorbar(aes(ymin=mean_long.leaf.cm-sem_long.leaf.cm,ymax=mean_long.leaf.cm+sem_long.leaf.cm),width=.2) +
  theme_classic() + scale_colour_manual(values=elev_three_palette)
```
